export const GET_ARTICLES = {
  START: "GET_ARTICLES_START",
  SUCCESS: "GET_ARTICLES_SUCCESS",
  ERROR: "GET_ARTICLES_ERROR"
};

export const LOGIN_USER = {
  START: "LOGIN_USER_START",
  SUCCESS: "LOGIN_USER_SUCCESS",
  ERROR: "LOGIN_USER_ERROR"
};

export const CREATE_ARTICLE = {
  START: "CREATE_ARTICLE_START",
  SUCCESS: "CREATE_ARTICLE_SUCCESS",
  ERROR: "CREATE_ARTICLE_ERROR"
};

export const INCREMENT_VIEWS = "INCREMENT_VIEWS";
